apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-ui
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: temporal-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Temporal"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - temporal.jwnwilson.co.uk
      secretName: temporal-tls
  rules:
    - host: "temporal.jwnwilson.co.uk"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-ui
                port:
                  number: 8080
