apiVersion: v1
kind: Secret
metadata:
  name: temporal-ui-auth
type: Opaque
stringData:
  provider-url: "https://YOUR_TENANT.auth0.com"
  client-id: "YOUR_AUTH0_CLIENT_ID"
  client-secret: "YOUR_AUTH0_CLIENT_SECRET"
  callback-url: "http://YOUR_NODE_IP:30823/auth/sso/callback"
---
apiVersion: v1
kind: Secret
metadata:
  name: aipet-secrets
type: Opaque
stringData:
  auth0-mgmt-client-id: "YOUR_M2M_CLIENT_ID"
  auth0-mgmt-client-secret: "YOUR_M2M_CLIENT_SECRET"
